### ISSUE TITLE
Last 8, Semi-Finals and Final

### ISSUE THREAD

**Issue by absentio** [inker/draw#7]
Why don't you develop those final steps? I don't have a clue about how to code them , but I am sure you should get it in a little piece of your time.

**Comment by inker** [comment]
@absentio 

Quarters (& on) draws are of no interest, since they are completely random, open draws with no constraints or limitations, where anyone can get anyone regardless of the country of origin and/or whether they've played each other before or not — unlike the group stage & last 16 draws which are an accurate simulation of how UEFA conduct them.

My top priority now is migrating the codebase to React.js which I'm already doing (slowly but surely) along with the major redesign. Other draws (Europa League included) will come later.
